/** @type {import('tailwindcss').Config} */

module.exports = {
  theme: {
    extend: {
      colors: {
        primary: "hsl(var(--primary) / <alpha-value>)",
        secondary: "hsl(var(--secondary) / <alpha-value>)",
        "primary-hover": "hsl(var(--primary-hover) / <alpha-value>)",
        "secondary-hover": "hsl(var(--secondary-hover) / <alpha-value>)",
        "gray-black": "hsl(var(--gray-black) / <alpha-value>)",
        "gray-dark": "hsl(var(--gray-dark) / <alpha-value>)",
        "gray-medium": "hsl(var(--gray-medium) / <alpha-value>)",
        "gray-light": "hsl(var(--gray-light) / <alpha-value>)",
        "gray-soft": "hsl(var(--gray-soft) / <alpha-value>)",
        background: "hsl(var(--background) / <alpha-value>)",
        soft: "hsl(var(--bg-soft) / <alpha-value>)",
        "surface-bg": "hsl(var(--surface-bg) / <alpha-value>)",
        "surface-text": "hsl(var(--surface-text) / <alpha-value>)",
        "surface-text-medium": "hsl(var(--surface-text-medium) / <alpha-value>)",
        "nav-text": "hsl(var(--nav-text) / <alpha-value>)",
        "nav-text-hover": "hsl(var(--nav-text-hover) / <alpha-value>)",
        "btn-primary-bg": "hsl(var(--btn-primary-bg) / <alpha-value>)",
        "btn-primary-hover": "hsl(var(--btn-primary-hover) / <alpha-value>)",
        "btn-primary-text": "hsl(var(--btn-primary-text) / <alpha-value>)",
        "bg-gradient-soft": "var(--bg-gradient-soft)",
        "bg-gradient-radial": "var(--bg-gradient-radial)",
        "bg-gradient-layered": "var(--bg-gradient-layered)",
        "border": "hsl(var(--border) / <alpha-value>)",
        "ring": "hsl(var(--ring) / <alpha-value>)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        heading: ["var(--font-heading)"],
      },
      // fontSize: {
      //   base: "var(--text-base)",
      //   xxs: "var(--text-xxs)",
      //   xs: "var(--text-xs)",
      //   sm: "var(--text-sm)",
      //   md: "var(--text-md)",
      //   lg: "var(--text-lg)",
      //   xl: "var(--text-xl)",
      //   "2xl": "var(--text-2xl)",
      //   "3xl": "var(--text-3xl)",
      //   "4xl": "var(--text-4xl)",
      //   "5xl": "var(--text-5xl)",
      // },
      // lineHeight: {
      //   tight: "var(--leading-tight)",
      //   normal: "var(--leading-normal)",
      //   relaxed: "var(--leading-relaxed)",
      // },
      // borderRadius: {
      //   sm: "var(--radius-sm)",
      //   md: "var(--radius-md)",
      //   lg: "var(--radius-lg)",
      //   xl: "var(--radius-xl)",
      //   "2xl": "var(--radius-2xl)",
      //   "3xl": "var(--radius-3xl)",
      //   "4xl": "var(--radius-4xl)",
      // },
      // boxShadow: {
      //   sm: "var(--shadow-sm)",
      //   md: "var(--shadow-md)",
      //   lg: "var(--shadow-lg)",
      //   xl: "var(--shadow-xl)",
      //   "2xl": "var(--shadow-2xl)",
      //   "3xl": "var(--shadow-3xl)",
      //   "4xl": "var(--shadow-4xl)",
      // },
      // spacing: {
      //   "xxs": "var(--space-xxs)",
      //   "xs": "var(--space-xs)",
      //   "sm": "var(--space-sm)",
      //   "md": "var(--space-md)",
      //   "lg": "var(--space-lg)",
      //   "xl": "var(--space-xl)",
      //   "2xl": "var(--space-2xl)",
      //   "3xl": "var(--space-3xl)",
      // },
    },
  }
}
